<!DOCTYPE html>
<html lang="en">
<head>
    <style>
 

    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
<?php 

// $name= "hamza bilal";

//  $course=  'web developing' ;

//  echo "i am <span id='a1'>".  $name . "</span>" , " ANd  i am learning about <span id='a2'>" . $course ."</span>" ;

                         
                //    ......       !!!OPREATERS!!!       ......
// $a=10;
// $b =30;

//  $c= $a + $b;

//  echo $c;
                // >>>>>>COMPERISSION<<<<<<
//  $a  =  20;
//  $b  =  30;
//  if( $a<=10 || $b>=29){
//     echo"true";
//  }
//  else{
//     echo"false";
//  }

//  if($a>10  &&  $b>40 ){
//     echo "true";
//  } else{
//     echo "false";
//  }


//    $name= "hamza";
   
//    $password= "1234567";


//    if($name="hamza"   &&     $password="1237"){

//     echo "and operatr";

//    } else{
//     echo "not and operator";
//    }
$a  =  "HAMZA";
$b   = 123456;
if($a  ="HAMZA"   &&  $b=12356){
   echo "its an and opreater";

}else{
   echo "its not an and opreater ";
}


?>






             





?>
</body>
</html>